// Navigation Routes
export const ROUTES = {
  SplashScreen: 'SplashScreen',
  WelcomeScreen: 'WelcomeScreen',
  RootMain: 'Main',
  Home: 'Home',
  CreateUserScreen: 'CreateUserScreen',
  VideoScreen: 'VideoScreen',
  VideoDetailsScreen: 'VideoDetailsScreen',
  ProfileScreen: 'ProfileScreen',
  UserDetailsScreen: 'UserDetailsScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  SettingsScreen: 'SettingsScreen',
  SignUp: 'SignUp',
  SignUpData: 'SignUpData',
  Login: 'Login',
  Drawer: 'Drawer',
  TabHome: 'TabHome',
  DrawerHome: 'DrawerHome',
  SearchResultList: 'SearchResultList',
  NotificationScreen: 'NotificationScreen',
};
